#!/bin/bash

# Setup RPC Key Script
# Helps configure RPC credentials for Zcash integration

set -e

ENV_FILE="../miden-browser-wallet/.env.local"

echo "🔑 Zcash RPC Key Configuration"
echo ""

# Check if .env.local exists
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env.local file..."
    touch "$ENV_FILE"
fi

# Get RPC endpoint
echo "Enter your RPC endpoint URL:"
echo "  Example: https://zcash-rpc.example.com"
read -r RPC_ENDPOINT

# Get credentials
echo ""
echo "Enter your RPC credentials:"
echo "  (If using API key, enter it for both username and password)"
echo ""
read -p "Username/API Key: " RPC_USER
read -sp "Password (leave empty if using API key only): " RPC_PASSWORD
echo ""

# Write to .env.local
cat > "$ENV_FILE" << EOF
# Zcash RPC Configuration
# Generated by setup-rpc-key.sh

NEXT_PUBLIC_ZCASH_RPC_ENDPOINT=$RPC_ENDPOINT
NEXT_PUBLIC_ZCASH_RPC_USER=$RPC_USER
NEXT_PUBLIC_ZCASH_RPC_PASSWORD=$RPC_PASSWORD

# Delegated Proving Service (optional)
NEXT_PUBLIC_ZCASH_PROVING_SERVICE=http://localhost:8080
EOF

echo ""
echo "✅ Configuration saved to $ENV_FILE"
echo ""
echo "Next steps:"
echo "1. Restart the wallet server: cd miden-browser-wallet && pnpm dev"
echo "2. Check RPC connection at http://localhost:3000/zcash"
echo ""

